### ISSUE TITLE
Public logging of the Emacs channel on Libera is forbidden 

### ISSUE THREAD

**Issue by shrysr** [wolandark/Artix-rice#1]
Please read https://www.emacswiki.org/emacs/EmacsChannelLogging and kindly do what is necessary regarding the logs you are sharing publicly >  https://github.com/wolandark/Artix-rice/blob/main/hexchat/logs/libera/%23emacs.log

Side note for your consideration: Perhaps other channels also have their own rules regarding public logging.

**Comment by wolandark** [comment]
thanks for the heads up! I was just trying to quickly back-up to migrate. I'll remove the logs.
